api:
  doc:
    name: @project.name@
    description: @project.description@
    version: @project.version@

spring:
  datasource:
    url: jdbc:h2:mem:capitoledb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always